#Requires -Version 7.0
<#
.SYNOPSIS
    Build (and optionally sign) an MSIX of the ExifGlass Windows head — one .msix
    per architecture, for direct download / GitHub Releases (sideload).

.DESCRIPTION
    ExifGlass ships on Windows as a sideloaded MSIX (there is no Microsoft Store
    flavour): every payload .exe/.dll ExifGlass owns is Authenticode-signed, then
    the whole .msix is signed. The package Identity/Publisher is set to the EXACT
    Subject of the signing certificate (a hard MSIX requirement); the artwork is
    rendered from the app logo (appxmanifest/Assets, generated by
    generate-msix-assets.ps1).

    If NO signing certificate is found the package is still produced — same
    identity/artwork — but left UNSIGNED (with a warning). Sign it before
    publishing; an unsigned MSIX cannot be installed.

    Pipeline (mirrors the ImageGlass MSIX packer):
      1. Publish a fresh self-contained NativeAOT build via publish.ps1 (so the
         package always matches the current source + ExifGlassVersion).
      2. Stage  <staging>\AppxManifest.xml + \Assets\* + \ExifGlass\<payload>.
      3. Fill the manifest template placeholders (identity, publisher, version, arch).
      4. Authenticode-sign ExifGlass's own payload binaries (the bundled third-party
         ExifTool — exiftool.exe + exiftool_files\ — is left as shipped by exiftool.org).
      5. Build resources.pri (makepri) so the manifest's unqualified logo names
         resolve to the scale-qualified assets per DPI.
      6. Pack the .msix (makeappx), then sign + verify the package.

    makeappx.exe / makepri.exe / signtool.exe are auto-located in the latest
    installed Windows 10/11 SDK; no PATH setup needed.

    Output: __artifacts/bundle/win/ExifGlass_<version>_win-<arch>.msix
    (<version> is <ExifGlassVersion> from Directory.Build.props.)

.PARAMETER Platform
    Target architecture: x64 (default) or arm64. Maps to the win-<arch> RID.

.PARAMETER Sign
    Attempt to Authenticode-sign the package (and payload). When no certificate is
    found the package is built UNSIGNED instead of failing. Omit to build an
    unsigned package without even looking for a certificate.

.PARAMETER CertSubject
    Substring of the code-signing certificate Subject to select it from the
    Current User / Local Machine "My" store (passed to signtool /n). Ignored when
    -CertFile is supplied. Default: "Duong Dieu Phap".

.PARAMETER CertFile
    Path to a PFX certificate to sign with instead of a store certificate.

.PARAMETER CertPassword
    Password for -CertFile (if any).

.PARAMETER TimestampUrl
    RFC-3161 timestamp server. Default: http://timestamp.sectigo.com

.PARAMETER PackageVersion
    Override the 4-part package version. Defaults to <ExifGlassVersion>.0
    (e.g. 2.0.0 -> 2.0.0.0).

.PARAMETER IdentityName
    MSIX package Identity Name. Default: "DuongDieuPhap.ExifGlass".

.PARAMETER PublisherDisplayName
    Human-readable publisher shown in the installer. Default: "Duong Dieu Phap".

.PARAMETER SkipPublish
    Reuse the existing __artifacts/publish/win-<arch> output instead of
    re-publishing (faster iteration; the package may not reflect uncommitted
    source changes).

.EXAMPLE
    pwsh __assets/win/pack-msix.ps1 -Platform x64 -Sign
    # Signed x64 package for GitHub Releases (cert selected by Subject).

.EXAMPLE
    pwsh __assets/win/pack-msix.ps1 -Platform arm64
    # Unsigned arm64 package (e.g. for local testing).

.EXAMPLE
    pwsh __assets/win/pack-msix.ps1 -Platform x64 -Sign -CertFile C:\eg.pfx -CertPassword hunter2
#>

[CmdletBinding()]
param(
    [ValidateSet('x64', 'arm64')]
    [string]$Platform = 'x64',

    [switch]$Sign,

    [string]$CertSubject = 'Duong Dieu Phap',
    [string]$CertFile = '',
    [string]$CertPassword = '',
    [string]$TimestampUrl = 'http://timestamp.sectigo.com',

    [string]$PackageVersion = '',

    [string]$IdentityName = 'DuongDieuPhap.ExifGlass',
    [string]$PublisherDisplayName = 'Duong Dieu Phap',

    [switch]$SkipPublish
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# --- Paths ---------------------------------------------------------------------
$SourceDir       = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$BuildProps      = Join-Path $SourceDir 'Directory.Build.props'
$PublishScript   = Join-Path $PSScriptRoot 'publish.ps1'
$GenAssetsScript = Join-Path $PSScriptRoot 'generate-msix-assets.ps1'
$ManifestTpl     = Join-Path $PSScriptRoot 'appxmanifest\AppxManifest.xml'
$AssetsDir       = Join-Path $PSScriptRoot 'appxmanifest\Assets'
$BundleDir       = Join-Path $SourceDir '__artifacts\bundle\win'

# --- Helpers -------------------------------------------------------------------

# Locate a Windows SDK tool (makeappx.exe / makepri.exe / signtool.exe), preferring
# the newest SDK and an x64 host build, falling back to whatever is on PATH.
function Find-SdkTool([string]$Name) {
    $roots = @(
        "${env:ProgramFiles(x86)}\Windows Kits\10\bin",
        "${env:ProgramFiles}\Windows Kits\10\bin"
    ) | Where-Object { $_ -and (Test-Path $_) }

    foreach ($root in $roots) {
        $hit = Get-ChildItem -Path $root -Directory -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -match '^10\.' } |
            Sort-Object { [version]$_.Name } -Descending |
            ForEach-Object { Join-Path $_.FullName "x64\$Name" } |
            Where-Object { Test-Path $_ } |
            Select-Object -First 1
        if ($hit) { return $hit }
    }

    $onPath = Get-Command $Name -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }

    throw "Could not find $Name. Install the Windows 10/11 SDK (includes makeappx, makepri & signtool)."
}

# Read a single <Tag>value</Tag> from Directory.Build.props.
function Get-BuildProp([string]$Tag) {
    $m = Select-String -Path $BuildProps -Pattern "<$Tag>(.*?)</$Tag>" | Select-Object -First 1
    if ($m) { return $m.Matches[0].Groups[1].Value.Trim() }
    return ''
}

# Find a usable signing certificate and report its EXACT Subject DN (needed for the
# manifest Publisher, which must match the signature byte-for-byte) and which store
# it lives in (so signtool searches the same one). Returns @{ Subject; Machine } or
# $null when none is found — the caller then builds an UNSIGNED package.
function Resolve-SigningCert {
    if ($CertFile) {
        if (-not (Test-Path $CertFile)) {
            Write-Warning "Certificate file not found: $CertFile"
            return $null
        }
        try {
            $c = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($CertFile, $CertPassword)
            return @{ Subject = $c.Subject; Machine = $false }
        }
        catch {
            Write-Warning "Could not load certificate '$CertFile': $($_.Exception.Message)"
            return $null
        }
    }
    foreach ($store in @(
            @{ Path = 'Cert:\CurrentUser\My';  Machine = $false },
            @{ Path = 'Cert:\LocalMachine\My'; Machine = $true })) {
        $c = Get-ChildItem $store.Path -CodeSigningCert -ErrorAction SilentlyContinue |
            Where-Object { $_.Subject -like "*$CertSubject*" -and $_.HasPrivateKey } |
            Select-Object -First 1
        if ($c) { return @{ Subject = $c.Subject; Machine = $store.Machine } }
    }
    return $null
}

# Sign one or more files with signtool (Authenticode, SHA-256, timestamped).
# Returns $true on success, $false on failure (never throws — the caller decides
# whether to continue UNSIGNED).
function Invoke-SignTool([string]$SignTool, [string[]]$Files, [bool]$UseMachineStore) {
    if ($Files.Count -eq 0) { return $true }
    $common = @('sign', '/fd', 'SHA256', '/tr', $TimestampUrl, '/td', 'SHA256')
    if ($CertFile) {
        $common += @('/f', $CertFile)
        if ($CertPassword) { $common += @('/p', $CertPassword) }
    }
    else {
        $common += @('/n', $CertSubject, '/a')
        # signtool /n defaults to the CurrentUser store; switch to the machine
        # store when that is where the certificate was found.
        if ($UseMachineStore) { $common += '/sm' }
    }
    & $SignTool @common @Files
    return ($LASTEXITCODE -eq 0)
}

# --- Version -------------------------------------------------------------------
$egVersion = Get-BuildProp 'ExifGlassVersion'
if (-not $egVersion) { throw "Could not read <ExifGlassVersion> from $BuildProps" }

# Package version is 4-part (MSIX requirement): <ExifGlassVersion> padded to X.Y.Z.0.
if ($PackageVersion) {
    $pkgVersion = $PackageVersion
}
else {
    $parts = @($egVersion.Split('.'))
    while ($parts.Count -lt 4) { $parts += '0' }
    $pkgVersion = ($parts[0..3] -join '.')
}

# --- Identity / publisher ------------------------------------------------------
$doSign = $false
$useMachineStore = $false
if ($Sign) {
    $cert = Resolve-SigningCert
    if ($cert) {
        $publisher       = $cert.Subject
        $doSign          = $true
        $useMachineStore = $cert.Machine
    }
    else {
        # No usable certificate — build UNSIGNED with a placeholder Publisher. It
        # must be signed before it can install.
        $publisher = "CN=$PublisherDisplayName"
        Write-Warning "No signing certificate found — building an UNSIGNED package."
    }
}
else {
    $publisher = "CN=$PublisherDisplayName"
}

# --- Output artifact -----------------------------------------------------------
$outMsix = Join-Path $BundleDir "ExifGlass_${egVersion}_win-$Platform.msix"

$flavour = if ($doSign) { 'SIGNED (sideload / GitHub)' }
           elseif ($Sign) { 'UNSIGNED — no certificate found' }
           else { 'UNSIGNED (no -Sign)' }
Write-Host "==> Packing ExifGlass $egVersion as MSIX ($Platform)"
Write-Host "    Flavour   : $flavour"
Write-Host "    Identity  : $IdentityName"
Write-Host "    Publisher : $publisher"
Write-Host "    Version   : $pkgVersion"
Write-Host "    Output    : $outMsix"

# --- Ensure the tile/store artwork exists (render it from the logo if not) ------
if (-not (Test-Path (Join-Path $AssetsDir '*.png'))) {
    Write-Host "    assets    : none found — generating from the app logo"
    & pwsh -NoProfile -ExecutionPolicy Bypass -File $GenAssetsScript
    if ($LASTEXITCODE -ne 0) { throw "Asset generation failed (exit $LASTEXITCODE)." }
}

# --- Locate SDK tools ----------------------------------------------------------
$makeappx = Find-SdkTool 'makeappx.exe'
$makepri  = Find-SdkTool 'makepri.exe'
$signtool = if ($doSign) { Find-SdkTool 'signtool.exe' } else { '' }
Write-Host "    makeappx  : $makeappx"
Write-Host "    makepri   : $makepri"
if ($doSign) { Write-Host "    signtool  : $signtool" }

# --- 1. Publish a fresh self-contained AOT build -------------------------------
$rid        = "win-$Platform"
$publishDir = Join-Path $SourceDir "__artifacts\publish\$rid"
$stagingDir = Join-Path $SourceDir "__artifacts\staging\$rid-msix"
$payloadDir = Join-Path $stagingDir 'ExifGlass'

if ($SkipPublish -and (Test-Path (Join-Path $publishDir 'ExifGlass.exe'))) {
    Write-Host ''
    Write-Host "==> Reusing publish output: $publishDir"
}
else {
    Write-Host ''
    Write-Host "==> Publishing $rid (Release, AOT, self-contained) via publish.ps1"
    if (Test-Path $publishDir) { Remove-Item $publishDir -Recurse -Force }
    # publish.ps1 kills any running ExifGlass/exiftool, prepends the VS Installer dir
    # to PATH (ILC needs vswhere) and publishes to __artifacts/publish/win-<arch>.
    & pwsh -NoProfile -ExecutionPolicy Bypass -File $PublishScript $Platform
    if ($LASTEXITCODE -ne 0) { throw "publish.ps1 failed for $rid (exit $LASTEXITCODE)." }
}
if (-not (Test-Path (Join-Path $publishDir 'ExifGlass.exe'))) {
    throw "Publish did not produce ExifGlass.exe in $publishDir"
}

# --- 2. Stage:  <staging>\AppxManifest.xml + \Assets\* + \ExifGlass\<payload> ---
Write-Host ''
Write-Host "==> Staging package layout"
if (Test-Path $stagingDir) { Remove-Item $stagingDir -Recurse -Force }
New-Item -ItemType Directory -Path $payloadDir -Force | Out-Null
Copy-Item -Path (Join-Path $publishDir '*') -Destination $payloadDir -Recurse -Force
# Drop debug symbols — they bloat the package and are not part of the product.
Get-ChildItem -Path $payloadDir -Recurse -Include '*.pdb' -File -ErrorAction SilentlyContinue |
    Remove-Item -Force
Copy-Item -Path $AssetsDir -Destination (Join-Path $stagingDir 'Assets') -Recurse -Force

# --- 3. Generate AppxManifest.xml from the template (UTF-8 BOM, as the SDK wants) -
$manifest = (Get-Content -Path $ManifestTpl -Raw).
    Replace('{{IDENTITY_NAME}}', $IdentityName).
    Replace('{{PUBLISHER}}', $publisher).
    Replace('{{PUBLISHER_DISPLAY_NAME}}', $PublisherDisplayName).
    Replace('{{VERSION}}', $pkgVersion).
    Replace('{{ARCH}}', $Platform)
$manOut = Join-Path $stagingDir 'AppxManifest.xml'
[System.IO.File]::WriteAllText($manOut, $manifest, [System.Text.UTF8Encoding]::new($true))

# --- 4. Sign ExifGlass's own payload binaries ----------------------------------
# The bundled ExifTool (exiftool.exe + its exiftool_files\ Perl runtime) is
# third-party (exiftool.org) and shipped verbatim — it is NOT re-signed.
if ($doSign) {
    $binaries = Get-ChildItem -Path $payloadDir -Recurse -Include '*.exe', '*.dll' -File |
        Where-Object { $_.FullName -notmatch '\\exiftool_files\\' -and $_.Name -ne 'exiftool.exe' } |
        Select-Object -ExpandProperty FullName
    Write-Host ''
    Write-Host "==> Signing $($binaries.Count) payload binary file(s)"
    if (-not (Invoke-SignTool -SignTool $signtool -Files $binaries -UseMachineStore $useMachineStore)) {
        Write-Warning "Could not sign payload binaries — the package will be left UNSIGNED."
        $doSign = $false
    }
}

# --- 5. Build the resource index (resources.pri) -------------------------------
Write-Host ''
Write-Host "==> Building resources.pri"
$priConfig = Join-Path (Split-Path $stagingDir) "$rid-msix.priconfig.xml"
$priOut    = Join-Path $stagingDir 'resources.pri'
if (Test-Path $priConfig) { Remove-Item $priConfig -Force }
& $makepri createconfig /cf $priConfig /dq en-US /o
if ($LASTEXITCODE -ne 0) { throw "makepri createconfig failed (exit $LASTEXITCODE)." }
& $makepri new /pr $stagingDir /cf $priConfig /mn $manOut /of $priOut /o
if ($LASTEXITCODE -ne 0) { throw "makepri new failed (exit $LASTEXITCODE)." }

# --- 6. Pack the .msix ---------------------------------------------------------
Write-Host ''
Write-Host "==> Packing the .msix"
New-Item -ItemType Directory -Path $BundleDir -Force | Out-Null
if (Test-Path $outMsix) { Remove-Item $outMsix -Force }
& $makeappx pack /o /d $stagingDir /p $outMsix
if ($LASTEXITCODE -ne 0) { throw "makeappx pack failed for $rid (exit $LASTEXITCODE)." }
Write-Host "    packed: $outMsix"

# --- Sign + verify the package -------------------------------------------------
if ($doSign) {
    Write-Host ''
    Write-Host "==> Signing the .msix"
    if (Invoke-SignTool -SignTool $signtool -Files @($outMsix) -UseMachineStore $useMachineStore) {
        Write-Host "==> Verifying signature"
        & $signtool verify /pa $outMsix
        if ($LASTEXITCODE -ne 0) { throw "signtool verify failed (exit $LASTEXITCODE)." }
    }
    else {
        Write-Warning "Could not sign the .msix — it has been left UNSIGNED."
        $doSign = $false
    }
}

# --- Done ----------------------------------------------------------------------
Write-Host ''
Write-Host 'Done.'
Write-Host "  Package : $outMsix"
if ($doSign) {
    Write-Host '  Signed  : yes (payload binaries + package)'
    Write-Host '  Next    : upload to the GitHub release for this version.'
}
else {
    Write-Host '  Signed  : no'
    Write-Host '  Next    : sign the .msix before publishing (an unsigned MSIX cannot be installed).'
}
